# Generated by Django 4.0.5 on 2022-06-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_band_active_band_biography_band_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.CharField(default='', max_length=1000, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='sold',
            field=models.BooleanField(default=True, verbose_name='Disponible ?'),
        ),
        migrations.AddField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('RC', 'Record'), ('CL', 'Clothing'), ('PO', 'Poster'), ('MI', 'Miscellaneous')], default='RC', max_length=5, verbose_name='Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Année'),
        ),
    ]
